site_name: point-collocation
site_description: Point-based lat/lon/time matchups against cloud-hosted NASA EarthData
  granules
repo_url: https://github.com/fish-pace/earthaccess_matchup
repo_name: fish-pace/earthaccess_matchup
theme:
  name: material
  palette:
  - scheme: default
    primary: blue
    accent: light blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: light blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.sections
  - navigation.expand
  - content.code.copy
extra_css:
- stylesheets/extra.css
nav:
- Home: index.md
- Examples:
  - Quickstart: quickstart.md
  - Level 3 matchups with PACE data: 1_l3_examples.md
  - Level 2 matchups with PACE data: 2_l2_examples.md
  - Large number of point matchups: 3_many_points.md
  - ICESat-2 ATL21 Matchups: 4_icesat2.md
  - Testing across multiple products: 5_more_products.md
- Installation: installation.md
- API Reference: api.md
- Contributing: contributing.md
- Releasing: releasing.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: true
          docstring_style: numpy
          show_root_heading: true
          show_signature_annotations: true
          separate_signature: true
markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
